version: '3.8'

services:
  main:
    container_name: main
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 4000:4000
      - 9229:9229
    command: bash -c "npx prisma generate && npx prisma migrate dev --name init && npm run dev"
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgres
    image: postgres:15
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql@15/data
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql@15/data
    restart: always

volumes:
  pgdata:
